title: Rohini Choudhari
logo: Images/35939857.jpeg
description: Healthcare Data Analyst | Medical Informaticist | Bridging Clinical Expertise with Health Tech
show_downloads: true
theme: jekyll-theme-minimal
